### ISSUE TITLE
Doesn't work between services

### ISSUE THREAD

**Issue by havenindustries** [govorov/ng-radio#2]
Is there a reason why I can do this across services?  So

Service 1 - 

this.radio.cast('message:bearer', authResult.idToken);

Service 2 - 

    radio.on('message:bearer').subscribe((message) => {
      alert('message:bearer: ' + message);
    });

Both have NgRadio injected.

**Comment by govorov** [comment]
Hi!
Please provide more details about the problem and how to reproduce it.
Thank you.
