### ISSUE TITLE
need off method

### ISSUE THREAD

**Issue by flashape** [govorov/ng-radio#3]
Can you add an .off() handler as well?  Or is there another way to accomplish that already?

**Comment by govorov** [comment]
Hi Rick,
As `radio.on` returns an ordinary observable, you can use rxjs `.unsubscribe()` to dispose a subscription:
```
const subscription = radio.on(someEvent).subscribe(() => {
    // callback
});

// and somewhere else:
subscription.unsubscribe();
```

**Comment by flashape** [comment]
Yes, I realized that after I posted...thanks!
